### ISSUE TITLE
ModuleNotFoundError: No module named 'amd'

### ISSUE THREAD

**Issue by xiaowangfeng** [jonathanBalasingham/Periodic-Set-Transformer#1]
I have successfully installed average-minimum-distance==1.3.6, but when running the main program, an error occurs:
ModuleNotFoundError: No module named 'amd'
how to solve it,thanks

**Comment by jonathanBalasingham** [comment]
Hi,

Could you check the packages your interpreter is using via ‘pip list’? This
is the correct way to install that dependency so this is a bit unusual.

**Comment by xiaowangfeng** [comment]
Thanks for your reply, my previous python was able to run CGCNN successfully. i installed average-minimum-distance==1.3.6 package library again and checked to make sure that it exists, so I don't know how to solve it when this problem occurs.

**Comment by xiaowangfeng** [comment]
I replaced import amd with import AMD and he would solve the above problem. 
But I have a new problem :
File ‘D:\Anaconda\envs\DL\lib\site-packages\torch\nn\modules\linear.py’, line 114, in forward
    return F.linear(input, self.weight, self.bias)
RuntimeError: Expected size for first two dimensions of batch2 tensor to be: [32, 128] but got: [32, 256]. 
I didn't change any of the code.
looking forward your replying.

**Comment by jonathanBalasingham** [comment]
Thank you for solving that. A bit unusual as `import amd` still works for me (ubuntu 20.04). Could I ask which file you're attempting to run?

**Comment by xiaowangfeng** [comment]
Sorry for the late reply, I'm running python main.py data. But I haven't got the right answer yet, the code keeps having problems.

**Comment by xiaowangfeng** [comment]
Sorry to bother you again, but I noticed that your code has a requirement for a dataset? why am I getting an error when I allow the code?  
In model.py, after the step output1 = x + self.out(att_output), the x and self.out(att_output) dimensions become inconsistent and error out.
I utilised the cif file inside the dataset https://github.com/YuanbinLiu/GANN/tree/main/demo/data

**Comment by jonathanBalasingham** [comment]
Ah, we added vector attention without the ability to use multiple attention heads so the problem stemmed from the default of num_heads=2. The problem should now be fixed as it has been reverted to standard DP attention. Please let me know if this fixed the issue. Standard DP attention is the one used in the paper, VA does produce better accuracy in general, but it is much slower.

**Comment by xiaowangfeng** [comment]
The problem isn't solved, I get an error for num_heads=2 when I run the code.

**Comment by jonathanBalasingham** [comment]
Apologies, the last commit was not pushed. The latest version has this problem fixed.

**Comment by xiaowangfeng** [comment]
The code is back to normal, thanks for the heads up. I will endeavour to make a small contribution to it!

**Comment by xiaowangfeng** [comment]
I have another question, why is it that when I train I have an MAE of 0.8 but when I test the MAE is reduced to 0.3 .

**Comment by jonathanBalasingham** [comment]
It would be difficult to say without having the data being tested. There could be a significant difference in the MAD of the test and train set. Is the training error from the last epoch? The model weights used are the ones that produce the best validation error, which might not be from the last epoch. What do the validation errors look like?

**Comment by xiaowangfeng** [comment]
The model doesn't look like it's taking random numbers because I'm getting the same results running the code on the same dataset. The problem I mentioned above is wrong, among other things it is that the MAE for val is always 0.8, but the MAE for test ends up being 0.3. The MAE during training is also 0.3.

**Comment by jonathanBalasingham** [comment]
Could you explain what you mean by "taking random numbers"? The torch weights are manually seeded so that results are deterministic for reproducibility.

**Comment by xiaowangfeng** [comment]
I'm sorry I misunderstood. You're right.

**Comment by jonathanBalasingham** [comment]
Can I go ahead and close this issue? Please let me know if any other problems exist

**Comment by xiaowangfeng** [comment]
of course.
